print("================================")
print("       LATVIEŠU DIEVĪBAS")
print("================================")
print()

print("1. Saule — saule, gaisma un auglība")
print()
print("Saule ir viena no nozīmīgākajām dievišķajām būtnēm latviešu")
print("mitoloģijā un folklorā. Viņa saistīta ar sauli, gaismu, dzīvību,")
print("auglību un dabas ciklisko ritējumu.")
print()
print("2. Laima — liktenis un cilvēka mūža gājums")
print()
print("Laima ir likteņa dievība latviešu mitoloģijā un folklorā.")
print("Viņa saistīta ar cilvēka mūža gājumu, likteni, dzimšanu")
print("un svarīgiem dzīves notikumiem.")
print()
print("3. Māra — zeme, mājas un auglība")
print()
print("Māra ir nozīmīga sievišķa dievība latviešu mitoloģijā un folklorā.")
print("Viņa saistīta ar zemi, mājām, auglību, mātes lomu un cilvēka")
print("materiālo dzīvi.")
print()
print("4. Pērkons — pērkons, zibens un taisnīgums")
print()
print("Pērkons ir pērkona un zibens dievība latviešu mitoloģijā.")
print("Viņš saistīts ar negaisu, spēku, taisnīgumu un cīņu pret")
print("ļaunajiem spēkiem.")
print()
print("5. Ūsiņš — pavasaris, zirgi un lauksaimniecība")
print()
print("Ūsiņš ir pavasara un zirgu dievība latviešu mitoloģijā.")
print("Viņš saistīts ar pavasara atnākšanu, gaismu, zirgiem un")
print("jaunā lauksaimniecības gada sākumu.")
print()
print("6. Dievs — debesis un pasaules kārtība")
print()
print("Dievs ir viena no augstākajām dievišķajām būtnēm latviešu")
print("mitoloģijā. Viņš saistīts ar debesīm, pasaules kārtību un")
print("kosmisko harmoniju.")
print()
print("7. Dēkla — bērnība un cilvēka liktenis")
print()
print("Dēkla ir viena no latviešu folklorā minētajām likteņa dievībām.")
print("Viņa īpaši saistīta ar bērna likteni, dzīves sākumu un")
print("cilvēka mūža gājumu.")