print("LATVIEŠU DIEVĪBAS")
print("=================")
print()

print("1. Saule")
print()
print("Saule ir viena no nozīmīgākajām dievišķajām būtnēm latviešu")
print("mitoloģijā un folklorā. Viņa saistīta ar sauli, gaismu, dzīvību,")
print("auglību un dabas ciklisko ritējumu.")
print()
print("2. Laima")
print()
print("Laima ir likteņa dievība latviešu mitoloģijā un folklorā.")
print("Viņa saistīta ar cilvēka mūža gājumu, likteni, dzimšanu")
print("un svarīgiem dzīves notikumiem.")