print("LATVIEŠU DIEVĪBAS")
print("=================")
print()

print("1. Saule")
print()
print("Saule ir viena no nozīmīgākajām dievišķajām būtnēm latviešu")
print("mitoloģijā un folklorā. Viņa saistīta ar sauli, gaismu, dzīvību,")
print("auglību un dabas ciklisko ritējumu.")
print()
print("2. Laima")
print()
print("Laima ir likteņa dievība latviešu mitoloģijā un folklorā.")
print("Viņa saistīta ar cilvēka mūža gājumu, likteni, dzimšanu")
print("un svarīgiem dzīves notikumiem.")
print()
print("3. Māra")
print()
print("Māra ir nozīmīga sievišķa dievība latviešu mitoloģijā un folklorā.")
print("Viņa saistīta ar zemi, mājām, auglību, mātes lomu un cilvēka")
print("materiālo dzīvi.")
print()
print("4. Pērkons")
print()
print("Pērkons ir pērkona un zibens dievība latviešu mitoloģijā.")
print("Viņš saistīts ar negaisu, spēku, taisnīgumu un cīņu pret")
print("ļaunajiem spēkiem.")
print()
print("5. Ūsiņš")
print()
print("Ūsiņš ir pavasara un zirgu dievība latviešu mitoloģijā.")
print("Viņš saistīts ar pavasara atnākšanu, gaismu, zirgiem un")
print("jaunā lauksaimniecības gada sākumu.")